import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StaitTransition from "@/components/StaitTransition";

export const metadata = {
  title: "Web Portfolio",
  description: "Generated by create next app",
};

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header/>
        <StaitTransition/>
        <PageTransition>
        {children}
        </PageTransition>
      </body>
    </html>
  );
}
